dashboard/blueprints/page/views.py
import json

from flask import Blueprint
from flask import current_app as app
from flask import redirect, render_template, request, session, url_for

import dataclasses as dc
from dashboard.utils import clean_dag_id
from dashboard.utils.vis import tree_diagram

page = Blueprint('page', __name__, template_folder='templates')

@page.route('/')
def index():
    dags_status_future = app.async_request_executor.submit(
        app.airflow_data_provider.get_dags_status)

    template_vars = {'etl_summary': dags_status_future.result()}
    if app.table_data_provider:
        template_vars['tables'] = app.async_request_executor.submit(app.table_data_provider.list, True).result()

    if app.links_data_provider:
        template_vars['links'] = app.async_request_executor.submit(app.links_data_provider.get_links).result()

    return render_template('index.html', **template_vars)


@page.route('/login')
def login():
    if 'GOOGLE_CLIENT_ID' in app.config:
        return render_template('login.html')
    else:
        return redirect(url_for('page.index'))


@page.route('/logout')
def logout():
    del session['user']
    return redirect(url_for('page.index'))


@page.route('/etl')
def etl_dashboard():
    etl_with_progress_future = app.async_request_executor.submit(
        app.etl_data_provider.etl_with_progress)
    history_future = app.async_request_executor.submit(
        app.airflow_data_provider.get_history, 14)

    return render_template('etl_dashboard.html',
                           etls=etl_with_progress_future.result(),
                           history=history_future.result())


@page.route('/etl/<string:dag_id>/<string:execution_date>')
def etl_details(dag_id, execution_date):
    name_without_version = clean_dag_id(dag_id)
    data = app.table_data_provider.get_tables_graph(dag_id, execution_date)
    return render_template('etl_details.html', name=name_without_version, data=data, raw=json.dumps(
        tree_diagram([{
            'id': v.id,
            'name': v.name,
            'success': v.get_graph_color(),
            'parent': v.parent} for v in data], width=800, height=800, padding=8)
    ))


@page.app_template_filter()
def describe_seconds(seconds):
    m, s = divmod(int(seconds), 60)
    h, m = divmod(m, 60)
    result = "{}s".format(s)
    if m > 0:
        result = "{}m {}".format(m, result)
    if h > 0:
        result = "{}h {}".format(h, result)
    return result


@page.route('/healthcheck')
def healthcheck():
    return "https://www.youtube.com/watch?v=I_izvAbhExY"


@page.errorhandler(500)
def internal_server_error(e):
    return render_template("500.html"), 200

dashboard/templates/layouts/base.html
<!DOCTYPE html>

<html lang="en">

<head>
  <base href="./">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

  {% block autorefresh %}<meta http-equiv="refresh" content="{{ config['REFRESH_RATE'] }}">{% endblock %}

  <title>{% block title %}{% endblock %}</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <!-- Icons-->
  <link href="https://unpkg.com/@coreui/icons/css/free.min.css" rel="stylesheet">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" rel="stylesheet">
  <!-- Main styles for this application-->
  <link rel="stylesheet" href="https://unpkg.com/@coreui/coreui/dist/css/coreui.min.css">

  <!-- base.css -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')}}">

  <script src="https://cdn.jsdelivr.net/npm/pace-js@1.0.2/pace.min.js"></script>

  <!-- Vega, vega-lite and vega-embedded -->
  <script src="https://cdn.jsdelivr.net/npm/vega@4.2.0"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-lite@2.6.0"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@3.18.1"></script>

  {% block css %}{% endblock %}
</head>

<body class="app header-fixed sidebar-hidden aside-menu-fixed">
  <header class="app-header navbar">
    <a class="navbar-brand" href="/">
      <img class="navbar-brand-minimized" src="https://image.flaticon.com/icons/png/128/439/439186.png" width="30"
        height="30" alt="CoreUI Logo">
      &nbsp; {{ config['COMPANY_NAME'] }} Data
    </a>

    <div class="navbarm">
      <ul class="nav navbar-nav">
        <li class="nav-item px-3">
          <a class="nav-link" href="{{ url_for('page.etl_dashboard') }}">ETLs</a>
        </li>
        {% for plugin in plugins.items() %}
        <li class="nav-item px-3">
          <a class="nav-link" href="{{ url_for(plugin[0] + '.index') }}">{{ plugin[1].tab_name }}</a>
        </li> 
        {% endfor %}
      </ul>
    </div>

    <ul class="nav navbar-nav ml-auto loginrefresh">
      <li class="nav-item refresh-info">

        <small>Page refreshed at: <b>{{ now.strftime('%H:%M:%S') }} UTC</b></small>
      </li>
      <li class="nav-item dropdown">
        {% if 'user' in session %}
        <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          <img class="img-avatar" src="{{ session.user.picture }}" alt="{{ session.user.email }}">
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-header text-center">
            <strong>Settings</strong>
          </div>
          <a class="dropdown-item" href="{{ url_for('page.logout') }}">
            <i class="fa fa-lock"></i> Logout</a>
        </div>
        {% endif %}
      </li>
    </ul>
  </header>
  <div class="app-body">
    <main class="main">
      <div class="breadcrumb-container">
        <!-- Breadcrumb-->
        <ol class="breadcrumb">
          {% block nav %}{% endblock %}
          <!-- Breadcrumb Menu-->
          <li class="breadcrumb-menu d-md-down-none">
          </li>
        </ol>
        <div class="app-help">
          ?
        </div>
      </div>
      <div class="container-fluid">
        {% block body %}{% endblock %}
      </div>
    </main>

    <!-- help model hidden -->
    <div class="help-modal">
      <p><b>ETLs</b> - information about the status of all ETL processes (DAGs) available in airflow database. If tables are defined this view shows number of processed tables. If tables information
      is missing, it shows number of tasks completed.</p>
      <p><b>Tables</b> - information available only it tables mapping is defined in a yaml file. It shows current status of processing related to a particular table.</p>
      <p><b>Plugins</b> - any information provided through plugins system available in discreETLy with appropriate tab name.</p>
      <p>For more information contact the team responsible for maintaining the dashboard or search the <a href="https://github.com/Wikia/discreETLy">documentation</a>.</p>
    </div>
  </div>
  <footer class="app-footer" style="display: none">
    <div>
      <a href="https://coreui.io">CoreUI</a>
      <span>&copy; 2018 creativeLabs.</span>
    </div>
    <div class="ml-auto">
      <span>Powered by</span>
      <a href="https://coreui.io">CoreUI</a>
    </div>
  </footer>
  <!-- CoreUI and necessary plugins-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/perfect-scrollbar@1.4.0/dist/perfect-scrollbar.common.min.js"></script>
  <script src="https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js"></script>
  <!-- Plugins and scripts required by this view-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-trendline@0.0.3/chartjs-plugin-trendline.js"></script>
  <script src="{{ url_for('static', filename='vendors/@coreui/coreui-plugin-chartjs-custom-tooltips/js/custom-tooltips.min.js') }}"></script>
  {% block charts %}{% endblock %}
  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
  <script>
    var helpButton = document.querySelector(".app-help");
    var helpInfo = document.querySelector(".help-modal");

    helpButton.addEventListener("click", (_) => {
      helpInfo.style.visibility === "visible" ? helpInfo.style.visibility = "hidden" : helpInfo.style.visibility = "visible"
    });
  </script>
  {% block js %}{% endblock %}
</body>

</html>

dashboard/templates/layouts/clean.html
<!DOCTYPE html>
<!--
* CoreUI - Free Bootstrap Admin Template
* @version v2.0.0
* @link https://coreui.io
* Copyright (c) 2018 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->

<html lang="en">
  <head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://unpkg.com/@coreui/coreui/dist/css/coreui.min.css">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body class="app header-fixed sidebar-hidden aside-menu-fixed">
    <div class="app-body">
      <main class="main">
        <div class="container-fluid">
{% block body %}{% endblock %}
        </div>
      </main>
    </div>
  </body>
</html>