dashboard/blueprints/page/__init__.py
from dashboard.blueprints.page.views import page

dashboard/blueprints/page/views.py
import json

from flask import Blueprint
from flask import current_app as app
from flask import redirect, render_template, request, session, url_for

import dataclasses as dc
from dashboard.utils import clean_dag_id
from dashboard.utils.vis import tree_diagram

page = Blueprint('page', __name__, template_folder='templates')

@page.route('/')
def index():
    dags_status_future = app.async_request_executor.submit(
        app.airflow_data_provider.get_dags_status)

    template_vars = {'etl_summary': dags_status_future.result()}
    if app.table_data_provider:
        template_vars['tables'] = app.async_request_executor.submit(app.table_data_provider.list, True).result()

    if app.links_data_provider:
        template_vars['links'] = app.async_request_executor.submit(app.links_data_provider.get_links).result()

    return render_template('index.html', **template_vars)


@page.route('/login')
def login():
    if 'GOOGLE_CLIENT_ID' in app.config:
        return render_template('login.html')
    else:
        return redirect(url_for('page.index'))


@page.route('/logout')
def logout():
    del session['user']
    return redirect(url_for('page.index'))


@page.route('/etl')
def etl_dashboard():
    etl_with_progress_future = app.async_request_executor.submit(
        app.etl_data_provider.etl_with_progress)
    history_future = app.async_request_executor.submit(
        app.airflow_data_provider.get_history, 14)

    return render_template('etl_dashboard.html',
                           etls=etl_with_progress_future.result(),
                           history=history_future.result())


@page.route('/etl/<string:dag_id>/<string:execution_date>')
def etl_details(dag_id, execution_date):
    name_without_version = clean_dag_id(dag_id)
    data = app.table_data_provider.get_tables_graph(dag_id, execution_date)
    return render_template('etl_details.html', name=name_without_version, data=data, raw=json.dumps(
        tree_diagram([{
            'id': v.id,
            'name': v.name,
            'success': v.get_graph_color(),
            'parent': v.parent} for v in data], width=800, height=800, padding=8)
    ))


@page.app_template_filter()
def describe_seconds(seconds):
    m, s = divmod(int(seconds), 60)
    h, m = divmod(m, 60)
    result = "{}s".format(s)
    if m > 0:
        result = "{}m {}".format(m, result)
    if h > 0:
        result = "{}h {}".format(h, result)
    return result


@page.route('/healthcheck')
def healthcheck():
    return "https://www.youtube.com/watch?v=I_izvAbhExY"


@page.errorhandler(500)
def internal_server_error(e):
    return render_template("500.html"), 200

dashboard/blueprints/page/templates/descriptions.html
{% extends 'layouts/base.html' %}
{% import 'macros/common.html' as common with context %}

{% block title %}Table {% endblock %}

{% block nav %}
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active">Tables dashboard</li>
{% endblock %}

{% block body %}

    <link href="{{ url_for('static', filename='css/descriptions.css') }}" rel="stylesheet">

    <div id="tooling">
        <div id="search">
            <input placeholder="&#x1F50D; Search"/>
            <div id="clear-search-container">
                <p id="clear-search">&times;</p>
            </div>
        </div>
        <div id="legend">
            Legend: <span class="cui-layers" aria-hidden="true"></span> Partition column
        </div>
    </div>

    <div id="table-container">
        <div class="row mt-3 table-header">
            <div class="col-3">
                <span id="all-toggle" class="toggle"><span class="cui-chevron-bottom" aria-hidden="true"></span></span>
                Database | Table name
            </div>
            <div class="col-9">Description</div>
        </div>
        {% for table_name, details in tables.items() %}
            <div id="{{ table_name }}" class="table-data">
                <div id="header-{{ table_name }}" class="row column-header-section">
                    <div class="col-3">
                        <span style="white-space: nowrap;">
                            <span id="toggle-{{ table_name }}" class="toggle row-toggle">
                                <span class="cui-chevron-bottom" aria-hidden="true"></span>
                            </span>
                            {{ table_name }}
                        </span>
                    </div>
                    <div class="col-9">{{ details.description }}</div>
                </div>
                <div class="row column-data-section" id="columns_{{ table_name }}">
                    <div class="row table-columns-header">
                        <div class="col-3">Column</div>
                        <div class="col-3">Type</div>
                        <div class="col-6">Description</div>
                    </div>
                    {% for column in details.columns %}
                        <div class="row column-data">
                            <div class="col-3">{{ column.name }} {% if column.is_partition %}<span class="cui-layers" aria-hidden="true"></span>{% endif %}</div>
                            <div class="col-3">{{ column.type }}</div>
                            <div class="col-6">{{ column.description }}</div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

{% block charts %}
    <script src="{{ url_for('static', filename='js/search.js') }}"></script>
    <script src="{{ url_for('static', filename='js/highlight.js') }}"></script>
    <script src="{{ url_for('static', filename='js/render_vis.js') }}"></script>
    <script>
        const collapsed_char = '<span class="cui-chevron-right" aria-hidden="true"></span>';
        const expanded_char = '<span class="cui-chevron-bottom" aria-hidden="true"></span>';


        expand_all = function () {
            $(".column-data-section").css("display", "block");
            $(".row-toggle").html(expanded_char);
            $("#all-toggle").html(expanded_char);
        };

        collapse_all = function () {
            $(".column-data-section").css("display", "none");
            $(".row-toggle").html(collapsed_char);
            $("#all-toggle").html(collapsed_char);
        };

        const search = new SearchProvider('.table-data');
        search.onSearchPhraseChanged = expand_all;
        search.main();

        window.onload = checkHighlight;

        //toggle visibility of a single row
        $(".column-header-section").click(function (event) {
            const tableName = $(this).attr('id').substr('header-'.length).replace(".", "\\.");
            const idColumns = "#columns_" + tableName;
            const idToggle = "#toggle-" + tableName;
            if ($(idToggle).html() === collapsed_char) {
                $(idColumns).css("display", "block");
                $(idToggle).html(expanded_char)
            } else {
                $(idColumns).css("display", "none");
                $(idToggle).html(collapsed_char)
            }
        });

        //toggle visibility of all rows
        $(".table-header").click(function (event) {
            if ($('#all-toggle').html() === collapsed_char) {
                expand_all();
            } else {
                collapse_all();
            }
        });
    </script>
{% endblock %}

dashboard/blueprints/page/templates/etl_dashboard.html
{% extends 'layouts/base.html' %}
{% import 'macros/common.html' as common with context %}

{% block title %}ETLs{% endblock %}

{% block nav %}
<li class="breadcrumb-item"><a href="/">Home</a></li>
<li class="breadcrumb-item active">ETL dashboard</li>

{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/etl_dashboard.css') }}">

<div id="tooling_help">
    <div id="tooling">
        <div id="search">
            <input placeholder="&#x1F50D; Search" />
            <div id="clear-search-container">
                <p id="clear-search">&times;</p>
            </div>
        </div>
    </div>
    <div id="help">
      <div>
          <p>Legend:</p>
      </div>
      <div>
          <p><span class="dot success">&#9673;</span> Success</p>
      </div>
      <div>
          <p><span class="dot running">&#9673;</span> In Progress</p>
      </div>
      <div>
          <p><span class="dot failed">&#9673;</span> Failure</p>
      </div>
    </div>
</div>

<div id="list-container">
    <div id="table-container">
        <div class="row mt-2 table-header">
            <div class="col-7 col-sm-5 col-md-4 col-xl-2">ETL name</div>
            <div class="col col-sm-3 col-md-2 col-xl-2 d-none d-sm-block">Latest run (UTC)</div>
            <div class="col-4 col-sm-4 col-md-2 col-xl-2">ETL state</div>
            <div class="col col-md-2 col-xl-2 d-none d-md-block">Duration (sec)</div>
            <div class="col-12 col-xl-4">Success | Failure</div>
        </div>
  {% for etl in etls|sort(attribute='name') %}
  <div class="row mt-2 etl-data">
    <div class="col-7 col-sm-5 col-md-4 col-xl-2 dag-name">
      <p>{{ etl.name }}</p>
    </div>
    <div class="col col-sm-3 col-md-2 col-xl-2 d-none d-sm-block">
      <p>
          {{ etl.schedule }}
      </p>
    </div>
    <div class="col-4 col-sm-4 col-md-2 col-xl-2">
      <a href="{{ config.AIRFLOW_WEBSERVER_BASE_URL }}/admin/airflow/tree?dag_id={{ etl.dag_id }}" target="_blank"  ><button type="button" class="btn status btn-{{ common.status_button_color(etl.state) }}">
          {% if etl.state == 'running' %}
            <span class="cil-speedometer"></span>
          {% endif %}
          {% if etl.tables_total %}
            {{ (etl.tasks_completed / etl.tasks_total * 100)|int }}% ({{ etl.tables_completed }} of {{ etl.tables_total }}) </button>
          {% else %}
            {{ (etl.tasks_completed / etl.tasks_total * 100)|int }}% ({{ etl.tasks_completed }} of {{ etl.tasks_total }}) </button>
          {% endif %}
      </a>
      <a href="{{ url_for('page.etl_details', dag_id=etl.dag_id, execution_date=etl.last_execution_date) }}">
        <img src="{{ url_for('static', filename='images/graph_icon.svg')}}" alt="Details">
      </a>
    </div>
    <div class="col col-md-2 col-xl-2 d-none d-md-block">
      {% if etl.duration_seconds %}<p>{{ etl.duration_seconds|describe_seconds }}</p>{% endif %}
    </div>
    <div class="col-12 col-xl-4">
      <p>
        {% for run in history[etl.name] %}
          <a href="{{ config.AIRFLOW_WEBSERVER_BASE_URL }}/admin/airflow/graph?execution_date={{ run.date }}&dag_id={{ etl.dag_id }}" class="dot {{ run.state }}"
            data-toggle="tooltip" data-placement="bottom" title="{{ run.date }}">&#9673;</a>
        {% endfor %}
      </p>
    </div>
  </div>
  {% endfor %}
</div>

<script src="{{ url_for('static', filename='js/search.js') }}"></script>
<script>
  let search = new SearchProvider('.etl-data');
  search.main();
</script>

{% endblock %}

dashboard/blueprints/page/templates/etl_details.html
{% extends 'layouts/base.html' %}
{% import 'macros/common.html' as common with context %}

{% block title %}ETL {{ name }} details{% endblock %}

{% block nav %}
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('page.etl_dashboard') }}">ETL dashboard</a></li>
    <li class="breadcrumb-item active">{{ name }}</li>

{%  endblock %}

{% block body %}

    <h2>Tables managed by {{ name }}</h2>

    <div class="card-body">
        <div id="graph"></div>
    </div>

    <script>
     new vega.View(vega.parse({{  raw|safe  }}))
            .renderer('svg') // set renderer (canvas or svg)
            .initialize('#graph') // initialize view within parent DOM container
            .run();
    </script>

    {# <h2>Tables in progress</h2> #}
{% endblock %}

dashboard/blueprints/page/templates/index.html
{% extends 'layouts/base.html' %}
{% import 'macros/common.html' as common with context %}

{% block title %}{{ config['COMPANY_NAME'] }} Data{% endblock %}

{% block nav %}
    <li class="breadcrumb-item active"><a href="/">Home</a></li>
{% endblock %}

{% block body %}

    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">

    <div class="row">
    <div class="col-6">
    
    {% set etl_failure = etl_summary | selectattr('state', 'eq', 'failed') | list | count > 0 %}

    <div id="etl-status" class="card{% if etl_failure %} text-white etl-danger {% endif %}" style="max-width: 18rem;">
        {% if etl_failure %}
            <div class="card-header etl-danger"><b>ETL status: FAILURE</b></div>
        {% else %}
            <div class="card-header etl-success"><b>ETL status: OK</b></div>
        {% endif %}

        <div class="card-body">
            {% if etl_failure %}
                <h5 class="card-title">List of failed ETLs</h5>
                <ul>
                    {% for etl in  etl_summary | selectattr('state', 'eq', 'failed') %}
                        <li>{{ etl.name }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <h5 class="card-title">Succeeded:
                <p class="status-box etl-success">{{ etl_summary | selectattr('state', 'eq', 'success') | list | count }}</p>
            </h5>
            <h5 class="card-title">Running:
                <p class="status-box etl-issue">{{ etl_summary | selectattr('state', 'eq', 'running') | list | count }}</p>
            </h5>

        </div>
    </div>

    {% if tables %}
    <div class="row">
        {% set tables_failure = tables | selectattr('state', 'eq', 'failed') | list | count > 0 %}


        <div class="col-12">
            <div class="card">
                <div class="card-header{% if tables_failure %} text-white etl-danger {% endif %}">
                    <b>Tables daily load status</b>
                </div>
                <div class="card-body">
                    {% if tables_failure %}
                        <h4>There are tables that failed to load toady, check <a href="{{ url_for('tables.index') }}">tables dashboard</a></h4>
                    {% endif %}
                    {% set today_tables = tables|
                                selectattr('state', 'eq', 'success')|
                                selectattr('last_update', 'ne', none)|
                                selectattr('last_update', 'gt', now.replace(hour=0, minute=0, second=0))|
                                list|
                                count %}
                    <h5 class="card-title">Daily load progress:
                        <p class="status-box etl-{% if today_tables == tables|count %}success{% else %}issue{% endif %}">
                            <b>{{ (today_tables/tables|count * 100)|int }}%</b>
                        </p>
                    </h5>
                    <p>Total tables: {{ tables|count }}</p>
                    <p>Tables updated today: {{ today_tables }}</p>
                    {% set stale_tables = tables|selectattr('last_update', 'ne', none)|selectattr('last_update', 'lt', now.replace(hour=0, minute=0, second=0))|list %}
                    {% if stale_tables|count > 0 %}
                        <p><b>Tables awaiting completion</b>:
                        <ul>
                            {% for table in stale_tables|batch(5)|first %}
                                <li>{{ table.id }}</li>
                            {% endfor %}
                            {% if stale_tables|count > 5 %}<li>...</li>{% endif %} {# we're showing 5 tables max #}
                        </ul>
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
    {% endif %}
    </div>
    
    <div class="col-6">
        <h2>Important links</h2>
        <ul>
            {% for link in links %}
                <li><a href="{{ link.url }}">{{ link.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    
    </div>
    
    
    
{% endblock %}

dashboard/blueprints/page/templates/login.html
{% extends 'layouts/clean.html' %}

{% block title %}data.wikia-services.com - login page{% endblock %}

{% block body %}

    <div class="text-center">
        <h3>Login to your {{  config.OAUTH_DOMAIN if config.OAUTH_DOMAIN is string else "/".join(config.OAUTH_DOMAIN)  }} account to access the site</h3>
    <p>
        <a href="{{  url_for('loginpass_google.login') }}"><button class="btn btn-primary">Proceed to Google Authentication</button></a>
    </p>
    </div>
{% endblock %}

dashboard/blueprints/page/templates/no_config.html
{% extends 'layouts/base.html' %}

{% block title %}{{ config['COMPANY_NAME'] }} Data - internal server error{% endblock %}

{% block nav %}

<li class="breadcrumb-item"><a href="/">Home</a></li>
{% if filename=="tables.yaml" %}
<li class="breadcrumb-item"><a href="/tables">Tables</a></li>
{% elif filename=="reports.yaml" %}
<li class="breadcrumb-item"><a href="/reports">Reports</a></li>
{% else %}
<li class="breadcrumb-item"><a href="/extra">Extra ETLS</a></li>
{% endif %}

{% endblock %} 

{% block body %}

    <div class="text-center">
        <h2>OOPS, this page is empty. But you can help me display 
            some data here if you create a valid {{ filename }} file, see the <a href="https://github.com/Wikia/discrETLy">docs</a>.</h2>
    </div>

{% endblock %}

dashboard/blueprints/page/templates/reports.html
{% extends 'layouts/base.html' %} {% import 'macros/common.html' as common with context %}

{% block title %}Reports{% endblock %}

{% block nav %}

<li class="breadcrumb-item"><a href="/">Home</a></li>
<li class="breadcrumb-item"><a href="/reports">Reports dashboard</a></li>

{% endblock %} {% block body %}
<link href="{{ url_for('static', filename='css/reports.css') }}" rel="stylesheet">

<div class="container">


    <div id="tooling_help">
        <div id="tooling">
            <div id="search">
                <input placeholder="&#x1F50D; Search" />
                <div id="clear-search-container">
                    <p id="clear-search">&times;</p>
                </div>
            </div>
        </div>
        <div id="help">
          <div>
              <p>Legend:</p>
          </div>
          <div>
              <p><span class="dot success">&#9673;</span> Success</p>
          </div>
          <div>
              <p><span class="dot running">&#9673;</span> In Progress</p>
          </div>
          <div>
              <p><span class="dot failed">&#9673;</span> Failure</p>
          </div>
          <div>
              <p><span class="dot root">&#9673;</span> Root Node</p>
          </div>
        </div>
    </div>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            {% for report in reports %}
            <div class="panel-heading" role="tab" id="heading{{ report.id }}">
                <h5 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ report.id }}"
                        aria-expanded="true" aria-controls="{{ report.id }}">
                        {{ report.name }}
                    </a>
                </h5>
            </div>
            <div id="{{ report.id }}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading{{ report.id }}">
                <div class="panel-body">
                    <div id="{{ report.id }}"></div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='js/render_vis.js') }}"></script>
<script src="{{ url_for('static', filename='js/search.js') }}"></script>
<script type="text/javascript">
    let search = new SearchProvider('.panel-heading');
    search.main();

    {% for report in reports %}
    render('#{{ report.id }}', {{report.data | safe}}); 
    {% endfor %}
</script> {% endblock %}

dashboard/blueprints/page/templates/table.html
{% extends 'layouts/base.html' %}
{% import 'macros/common.html' as common with context %}

{% block title %}Table {{ name }} details{% endblock %}

{% block nav %}
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/tables">Tables dashboard</a></li>
    <li class="breadcrumb-item active">Table {{ name }}</li>
{%  endblock %}

{% block body %}
    <canvas id="chart"></canvas>
{% endblock %}

{% block charts %}
    <script>
        new Chart(document.getElementById('chart').getContext('2d'),
        {
			type: 'line',
			data: {
				labels: [{{ counts | map(attribute=0) | map('tojson') | join(',') }}],
				datasets: [{
				    label: 'Record count',
					backgroundColor: 'rgb(255, 99, 132)',
					borderColor: 'rgb(255, 99, 132)',
					data: [
                        {{ counts | map(attribute=1) | join(',') }}
					],
					fill: false,
                    trendlineLinear: {
                        style: "rgba(255,105,180, .8)",
                        width: 2
                    },
				}]
			},
            options: {
				responsive: true,
				title: {
					display: true,
					text: 'Record count per day'
				},
				tooltips: {
					mode: 'index',
					intersect: false,
				},

				hover: {
					mode: 'nearest',
					intersect: true
				},
				scales: {
					xAxes: [{
						display: true,
						scaleLabel: {
							display: true,
							labelString: 'Day'
						}
					}],
					yAxes: [{
						ticks: {
							beginAtZero:true
						},
						display: true,
						scaleLabel: {
							display: true,
							labelString: 'Records'
						}
					}]
				}
			}
		});
    </script>
{% endblock %}

dashboard/blueprints/page/templates/table_dashboard.html
{% extends 'layouts/base.html' %}
{% import 'macros/common.html' as common with context %}

{% block title %}Tables{% endblock %}

{% block nav %}
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active">Tables dashboard</li>
{%  endblock %}

{% block body %}

<link href="{{ url_for('static', filename='css/table_dashboard.css')}}" rel="stylesheet">

<div id="tooling">
        <div id="search">
                <input placeholder="&#x1F50D; Search" />
                <div id="clear-search-container">
                    <p id="clear-search">&times;</p>
                </div>
            </div>
</div>

<div id="table-container">
    <div class="row mt-3 table-header">
        <div class="col-9 col-sm-6 col-md-4">Database | Table name</div>
        <div class="col col-sm-3 col-md-3 d-none d-sm-block">Last update</div>
        <div class="col-3 col-sm-3 col-md-2">Status</div>
        <div class="col-md-3 d-none d-md-block">Record count</div>
    </div>
{% for table in tables %}
<div id="{{ table.id.split('.')[1] }}" class="row mt-3 table-data">
  <div class="col-9 col-sm-6 col-md-4">
    <p>
        {% if table.link_descriptions %}<a href="descriptions#{{ table.id }}">{% endif %}
        {{ table.id }}
        {% if table.link_descriptions %}</a>{% endif %}
        {% if table.active_alerts %}
            {% for alert in table.active_alerts %}
                <a href="{{ alert.link }}" target="_blank"><i class="cui-circle-x text-danger" data-toggle="tooltip" data-placement="bottom" title="Alert triggered {{ alert.name}}"></i></a>
            {% endfor %}
        {% else %}
            <i class="cui-circle-check text-success" data-toggle="tooltip" data-placement="bottom" title="No active alerts"></i>
        {% endif %}
    </p>
  </div>
  <div class="col col-sm-3 col-md-3 d-none d-sm-block">
      {% if table.last_update %}{{ table.last_update.strftime('%Y-%m-%d %H:%M:%S') }}{% else %}Unknown{% endif %}
  </div>
  <div class="col-3 col-sm-3 col-md-2">
    <a href="/tables/{{ table.id }}" role="button" class="btn btn-{{ common.status_button_color(table.state) }}" {% if table.load_duration_seconds %}data-toggle="tooltip" data-placement="bottom" title="Load duration: {{ table.load_duration_seconds|describe_seconds }}"{% endif %}>
        {{ table.state }}
    </a>
  </div>
  <div class="col-md-3 d-none d-md-block">
    {% if table.counts %}
        <canvas id="canvas_{{ table.id }}" height="30" width="30" style="cursor: pointer;" onClick="window.location='/tables/{{ table.id }}';"></canvas>
    {% endif %}
  </div>
</div>
{% endfor %}

</div>

{% endblock %}

{% block charts %}
    <script>
    {% for table in tables %}
        // {{ table }}
        {% if table.counts %}

        new Chart(document.getElementById('canvas_{{ table.id }}').getContext('2d'),
        {
			type: 'bar',
			data: {
				labels: [{{ table.counts | map(attribute=0) | map('tojson') | join(',') }}],
				datasets: [{
					backgroundColor: 'rgb(255, 99, 132)',
					borderColor: 'rgb(255, 99, 132)',
					data: [
                        {{ table.counts | map(attribute=1) | join(',') }}
					],
					fill: false,
				}]
			},
			options: {
				responsive: true,
                maintainAspectRatio: false,
				tooltips: {
				    enabled: false,
					mode: 'index',
                    axis: 'y',
					intersect: false,
				},
				hover: {
				    display: false,
					mode: 'nearest',
					intersect: true
				},
                legend: {
				    display: false
                },
				scales: {
					xAxes: [{
						display: false
					}],
					yAxes: [{
						display: false,
						scaleLabel: {
							display: true,
							labelString: 'Records'
						}
					}]
				}
			}
		});
    {% endif %}

    {% endfor %}
    </script>

    <script src="{{ url_for('static', filename='js/search.js') }}"></script>
    <script src="{{ url_for('static', filename='js/highlight.js') }}"></script>
    <script src="{{ url_for('static', filename='js/render_vis.js') }}"></script>
    <script>
        let search = new SearchProvider('.table-data');
        search.main();

        window.onload = checkHighlight;
      </script>
{% endblock %}